name: Create Attachomation Release

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Build plugin
              run: |
                  bun install
                  bun run build
          
            - name: Zip files
              run: |
                  zip attachomation.zip main.js manifest.json

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  gh release create "$tag" \
                      --title="$tag" \
                      --draft \
                      main.js manifest.json attachomation.zip
